Team-Elancer/elancer-clone

.eslintrc.js, src/App.jsx, src/components/Button/FilterButton/index.jsx, src/components/Button/FilterButton/style.js, src/components/ListFreelancer/index.jsx, src/components/ListFreelancer/style.js, src/pages/ListPartner/index.jsx, src/pages/ListPartner/style.js, src/styles/GlobalStyles.js, src/utils/constants/responsive.js
=> add: 미디어쿼리 세팅 + 프리랜서 보기 페이지

src/components/Button/FilterButton/index.jsx, src/components/Button/FilterButton/style.js
=> fix: naming convention

src/App.jsx
=> fix: routing - /list-partner

src/components/Button/FilterButton/style.js, src/components/ListFreelancer/index.jsx, src/components/ListFreelancer/style.js, src/pages/ListPartner/style.js, src/styles/GlobalStyles.js
fix: pages/list-partner 모바일 & 데스크탑 스타일링
=> fix: pages/list-partner 모바일 & 데스크탑 스타일링

src/components/ListFreelancer/index.jsx, src/pages/ListPartner/index.jsx
add: pages/lister-partner Footer 추가
=> add: pages/lister-partner Footer 추가

src/components/ListFreelancer/index.jsx, src/layouts/Footer/index.jsx
=> fix: key값 수정

src/components/InfoDetail/index.jsx, src/components/InfoDetail/style.js, src/pages/Partner/PartnerDetail/index.jsx
=> add: 프로젝트 & 이력서 페이지

src/components/InfoDetail/index.jsx, src/components/InfoDetail/style.js
=> add: InfoDetail/소셜미디어 버튼

src/components/Project-Ecard/index.jsx, src/components/Re-Freelancer/index.jsx, src/pages/Partner/PartnerDetail/index.jsx, src/pages/Project/ProjectDetail/index.jsx, src/pages/Project/ProjectDetail/style.js
=> add: 프로젝트 보기 상세페이지

src/layouts/Footer/style.js, src/pages/Project/ProjectDetail/style.js
=> fix: Footer 컴포넌트 스타일링

src/layouts/Footer/style.js
=> fix: Footer 컴포넌트  패딩 조절

src/pages/MyBoardFreelancer/MyBoardManageProject/index.jsx, src/pages/MyBoardFreelancer/MyBoardOnGoing/index.jsx
fix:(naming) myboardproject -> BoardCardSpan
=> fix:(naming) myboardproject -> BoardCardSpan

src/components/Myboard/CardSpan/index.jsx, src/pages/DashBoard/Enterprise/index.jsx, src/pages/DashBoard/Project/index.jsx
fix: page/dashboard (naming) myboardproject -> BoardCardSpan
=> fix: page/dashboard (naming) myboardproject -> BoardCardSpan

src/App.jsx, src/components/Modal/DashBoardContact/index.jsx, src/hooks/useCloseOutside/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/style.js, src/pages/MyBoardFreelancer/index.jsx
=> Myboard freelancer

src/App.jsx, src/components/Button/CategoryFAQButton/index.jsx, src/components/Button/CategoryFAQButton/style.js, src/layouts/Footer/style.js, src/pages/ContactFAQ/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/index.jsx
=> add: pages/contact/faq

src/pages/ContactFAQ/CategoryFAQButton/style.js, src/pages/ContactFAQ/FAQLists/style.js
add: Media queries for pages/FAQ
=> add: Media queries for pages/FAQ

src/pages/MyBoardFreelancer/MyBoardCareer/index.jsx, src/pages/MyBoardFreelancer/MyBoardCareer/style.js
add: myboard-career upload (feat)
=> add: myboard-career upload (feat)

src/App.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/JobField/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/JobField/style.js, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/style.js, src/pages/MyBoardFreelancer/MyBoardCareer/index.jsx, src/pages/MyBoardFreelancer/MyBoardCareer/style.js
=> Myboard freelancer account

src/App.jsx, src/components/Myboard/LeftMenu/Freelancer/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/JobSkill/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/JobSkill/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/DeveloperSkillList.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/style.js
add: pages/myboard-freelancer/profile-modify
=> add: pages/myboard-freelancer/profile-modify

src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/style.js
adding: page/myboardprofilemodify
=> adding: page/myboardprofilemodify

src/pages/MyBoardFreelancer/MyBoardAccount/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/style.js
adding: pages/profile-modify ->career-textarea
=> adding: pages/profile-modify ->career-textarea

.eslintrc.js, package-lock.json, package.json, src/pages/Login/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/index.jsx, src/pages/SignUp/Freelancer/index.jsx
feat: access token & calendar format fixing bugs
=> feat: access token & calendar format fixing bugs

.eslintrc.js, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: add pages/myboard-freelancer/account - GET API
=> feat: add pages/myboard-freelancer/account - GET API

src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/index.jsx
add: (pages/freelancer-account) PUT API
=> add: (pages/freelancer-account) PUT API

src/pages/MyBoardFreelancer/MyBoardAccount/JobField/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/JobField/style.js, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/index.jsx, src/utils/config/api.js
add: axios API config & fix: working on REST API(PUT)
=> add: axios API config & fix: working on REST API(PUT)

src/pages/Login/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/JobField/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx
add: pages/myboard/account - job field & added Login function
=> add: pages/myboard/account - job field & added Login function

src/pages/MyBoardFreelancer/MyBoardAccount/JobField/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx
feat: (add) - pages/myboard/account - API PUT
=> feat: (add) - pages/myboard/account - API PUT

src/components/DaumPostCode/index.jsx, src/components/DaumPostCode/style.js, src/pages/MyBoardFreelancer/MyBoardAccount/JobField/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/style.js, src/pages/MyBoardFreelancer/index.jsx, src/pages/SignUp/Freelancer/index.jsx, src/pages/SignUp/Freelancer/style.js
feat: (add) pages/myboard/account API 90% finished
=> feat: (add) pages/myboard/account API 90% finished

src/components/Modal/ModalFreelancerContact/index.jsx, src/components/Modal/ModalFreelancerContact/style.js, src/pages/DashBoard/Contact/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/ContactOneOnOne/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/ContactOneOnOne/style.js, src/pages/MyBoardFreelancer/MyBoardContact/index.jsx
add: pages/myboard/contact -> finished CRUD
=> add: pages/myboard/contact -> finished CRUD

src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx
feat: adding  /freelancer-profile/academic-ability API
=> feat: adding  /freelancer-profile/academic-ability API

src/pages/DashBoard/Profile/index.jsx, src/pages/DashBoard/Profile/style.js, src/pages/Main/Enterprise/index.jsx, src/pages/Main/Enterprise/style.js
1.잡필드가 개발일때만 해당하는 스킬만 나오고 각 스킬이  같은게 2개이상이면 배열에서 삭제
2. ","가 스킬이 선택할때마다 추가되며 스킬이 사라질때 같이 삭제 
3. 해당 스킬이 선택되면 버튼 css변경
=> 엔터프라이즈 메인페이지 스킬 선택 모달 개발 기술추가

src/components/DashBoard/Comapany-Myboard/index.jsx, src/pages/DashBoard/Profile/index.jsx
1. 연간 매출액,사업자 등록번호 데이터 추가
2. 활동평가 및 점수 데이터 추가
3. 점수 데이터가 변경될때마다 별 색상 변경
=> 프로필관리 데이터 새로 추가 및 별 색상변경

src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/CareerTemplate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: adding pages/profile-modify ->  PUT /freelancer-profile/career
=> feat: adding pages/profile-modify ->  PUT /freelancer-profile/career

src/pages/MyBoardFreelancer/MyBoardContact/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/CareerTemplate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/Certificate/EducationTemplate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/Certificate/LanguageTemplate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/Certificate/LicenseTemplate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/Certificate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/style.js
feat: added PUT /freelancer-profile/education-license-language
=> feat: added PUT /freelancer-profile/education-license-language

src/pages/Main/Enterprise/index.jsx, src/pages/Main/Enterprise/style.js
1. 더보기 버튼 링크추가
2. 빈공간 display : none으로 삭제
3. width 수정 중간으로 맞추기 위해
=> 엔터프라이즈 메인 css변경

src/pages/MyBoardFreelancer/MyBoardProfileModify/ProfileIntro/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/style.js
feat: added PUT /freelancer-profile/intro
=> feat: added PUT /freelancer-profile/intro

src/components/DashBoard/Company-Account/index.jsx, src/components/DashBoard/Company-Account/style.js, src/pages/Login/index.jsx, src/pages/Login/style.js, src/pages/SignUp/Company/index.jsx, src/pages/SignUp/Freelancer/index.jsx, src/pages/SignUp/Freelancer/style.js
1. 중복되지 않는 함수는 익명함수로 변경
2. 경고문이 필요할때만 나타나게 수정
3. caps-lock인식 가능하게 수정
=> 함수 간소화 및 경고문 수정

src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/Designer/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/ETC/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/JobSkill/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/JobSkill/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/ProjectManager/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/index.jsx, src/utils/constants/freelancerPosition/designer.js, src/utils/constants/freelancerPosition/developer.js, src/utils/constants/freelancerPosition/etc.js, src/utils/constants/freelancerPosition/planner.js, src/utils/constants/freelancerPosition/publisher.js
feat: added 스킬 template (front only)
=> feat: added 스킬 template (front only)

src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/Designer/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/Developer/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/ETC/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/ProjectManager/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/Publisher/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/style.js
feat: added '주언어 & 역할' pages/profile-modify  스킬'
=> feat: added '주언어 & 역할' pages/profile-modify  스킬'

src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/index.jsx
feat: fixed pages/profile-modify - CareerInfo STATE bugs
=> feat: fixed pages/profile-modify - CareerInfo STATE bugs

src/layouts/Header/index.jsx, src/pages/Main/Freelancer/index.jsx
=> fixed: styling

src/components/Modal/ProjectDetail/index.jsx, src/components/Modal/ProjectDetail/style.js, src/components/Project-Ecard/index.jsx, src/components/Re-Project/index.jsx, src/layouts/Footer/style.js, src/layouts/Header/index.jsx, src/layouts/Header/style.js, src/pages/Main/Enterprise/style.js, src/pages/Project/ProjectNewDetail/index.jsx, src/pages/Project/index.jsx
1.헤더 프로젝트 디테일 페이지에 맞게 배경색 및 로고 변경
2. 프로젝트 디테일 페이지 css 완료 및 모달 추가
3. 기존 프로젝트 클릭시 이동하는 링크 변경
=> 헤더 배경색 및 로고 페이지에 맞게 변경, 프로젝트 디테일 페이지 완료 모달까지

src/components/MenuBar/Enterprise/index.jsx, src/components/MenuBar/Enterprise/style.js, src/components/MenuBar/index.jsx, src/pages/Project/index.jsx
1. 엔터프라이즈 메뉴바 안나오던가 나오게 수정
2. 기존 project 메인부분 삭제 안된거 수정
=> 메뉴바 프리랜서 추가되어 엔터프라이즈도 수정

src/pages/Login/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProjectHistory/index.jsx, src/pages/MyBoardFreelancer/index.jsx, src/utils/config/api.js
feat: fixed form cannot appear as a descendant of form
=> feat: fixed form cannot appear as a descendant of form

src/pages/Login/index.jsx
1. 로컬스토리지에 멤버타입이 기업이면 기업으로 프리랜서면 프리랜서 메인화면으로 이동
=> 로딩하면 멤버타입에 따라 각 메인화면으로 이동

src/pages/DashBoard/index.jsx, src/pages/Main/Enterprise/index.jsx
=> 엑세스토큰 만료및 refreshtoken 만료 수정

src/components/Modal/ModalFreelancerContact/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/ContactOneOnOne/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/index.jsx, src/pages/MyBoardFreelancer/index.jsx, src/utils/config/api.js
feat: fixing bugs for refresh token & pages/myboardAccount
=> feat: fixing bugs for refresh token & pages/myboardAccount

src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: fixing bugs for pages/myboard-account -> default value
=> feat: fixing bugs for pages/myboard-account -> default value

src/hooks/useFetchRefreshToken/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: cleaning code for refresh token and & adding refresh token hooks
=> feat: cleaning code for refresh token and & adding refresh token hooks

src/pages/MyBoardFreelancer/MyBoardContact/ContactOneOnOne/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: fixed bugs for contact/edit
=> feat: fixed bugs for contact/edit

src/App.jsx, src/components/PrivateRoute/index.jsx
feat: adding protected route for pages/myboard
=> feat: adding protected route for pages/myboard

src/hooks/useFetchRefreshToken/index.jsx, src/pages/MyBoardFreelancer/MyBoardManageProject/index.jsx, src/pages/MyBoardFreelancer/MyBoardOnGoing/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfile/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProfileIntro/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: added detail & simple API(get) 페이지 작업
=> feat: added detail & simple API(get) 페이지 작업

src/components/Re-Project/index.jsx, src/components/Re-Project/style.js, src/pages/DashBoard/ProjectAdd/index.jsx, src/pages/Main/index.jsx
1. 추천 프로젝트 데이터 불러옴
2. 개발자인이 기타인지 직업 데이터 요청
3. 배경색 데이터 요청
=> 메인화면 추천프로젝트 get으로 데이터 불러옴

src/components/Re-Project/index.jsx
=> 경력, 주소, 월단가 함수사용하여 원하는 값만 가져옴

src/components/FreelancerDetail/index.jsx, src/components/FreelancerDetail/style.js, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/Certificate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/EducationInfoTemplate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProjectHistory/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: refactoring for pages/educationInfo due to API issue & adding API(PUT) for detail/simple
=> feat: refactoring for pages/educationInfo due to API issue & adding API(PUT) for detail/simple

src/components/FreelancerDetail/index.jsx, src/components/Project-Ecard/index.jsx, src/components/Re-Project/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/index.jsx, src/pages/MyBoardFreelancer/MyBoardManageProject/index.jsx, src/pages/MyBoardFreelancer/MyBoardOnGoing/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProfileIntro/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProjectHistory/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/Publisher/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/index.jsx, src/pages/MyBoardFreelancer/index.jsx, src/pages/Partner/PartnerDetail/index.jsx
feat: adding profile-modify/skill/publisher & fixing useContext for Outlook format
=> feat: adding profile-modify/skill/publisher & fixing useContext for Outlook format

src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/Designer/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/Developer/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/ETC/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/JobSkill/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/ProjectManager/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/Publisher/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: fixed API bugs -> positionType & finished API for skills
=> feat: fixed API bugs -> positionType & finished API for skills

src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/Certificate/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: added Certificate, Education and License API(GET&PUT)
=> feat: added Certificate, Education and License API(GET&PUT)

src/components/FreelancerDetail/index.jsx
feat: added Freelancer Profile -  Resume Detail
=> feat: added Freelancer Profile -  Resume Detail

src/components/Button/SubmitButton/index.jsx, src/components/DashBoard/Project-List/index.jsx, src/components/Modal/ProjectInterview/index.jsx, src/pages/DashBoard/Project/Main/index.jsx, src/pages/DashBoard/Project/index.jsx, src/pages/DashBoard/index.jsx
1. 프로젝트 모달 지원자 post로 기업 프로젝트 인터뷰 요청 완료
2. useEffect로 post되면 인터뷰 요청자 목록 최신화
=> 프로젝트 리스트 모달 인터뷰요청 post 및 useEffect로 목록 최신화

src/components/Re-Project/index.jsx, src/pages/Main/index.jsx, src/pages/Project/ProjectNewDetail/index.jsx, src/pages/SignUp/Company/index.jsx, src/pages/SignUp/Finish/index.jsx, src/pages/SignUp/Freelancer/index.jsx
1. 디테일페이지 미로그인시 에러나는거 get할때 header가 들어가 있어서 미로그인시에는 header를 뺌
2. 회원가입후 토큰 넣어서 저절로 로그인 해서 알맞는 메인화면으로 이동 저절로 로그인하는 기능이 프리랜서에는 없어서 추가
=> 프로젝트 디테일페이지 로그인 안됬을때 에러 수정 프리랜서 회원가입시 토큰들어가게 설정

src/components/DashBoard/Project-List/index.jsx, src/pages/DashBoard/ProjectAdd/index.jsx, src/pages/DashBoard/ProjectAdd/style.js, src/pages/DashBoard/index.jsx
1. 프로젝트 등록 달력 laptop사이즈 input 위치 조정
2. 프로젝트 리스트 지원자 및 인터뷰 카운트 가 문의 페이지 갔다가 오면 에러가 나서 usestate추가하여 해결
=> 프로젝트 등록 달력input 위치 조정(css), 프로젝트 리스트 오류 해결

src/components/Modal/ModalFreelancerContact/index.jsx, src/hooks/useBeforeUnload/index.jsx, src/hooks/useConfirm/index.jsx, src/pages/ContactFAQ/FAQLists/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/ContactOneOnOne/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/style.js, src/pages/MyBoardFreelancer/MyBoardOnGoing/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/MyBoardFreelancer/index.jsx
feat: refactoring for pages/myboard-freelancer/contact & added custom hooks for useBeforeUnload and useConfirm
=> feat: refactoring for pages/myboard-freelancer/contact & added custom hooks for useBeforeUnload and useConfirm

src/components/DashBoard/Project-List/index.jsx, src/components/Myboard/CardSpan/index.jsx, src/pages/DashBoard/Project/Interview/index.jsx, src/pages/DashBoard/Project/Main/index.jsx, src/pages/DashBoard/Project/Participate/index.jsx, src/pages/DashBoard/Project/index.jsx
1. card span에서 프로젝트 개수가 나오게 api추가 
2. 프로젝트 main 리스트 api변경으로 수정
3. 지원현황 ,인터뷰 요청 get url 변경 및 api 데이터 변경으로 인한 수정
=> card span에 프로젝트 개수 추가 및 프로젝트 리스트 main url변경

src/pages/DashBoard/Project/Finish/index.jsx, src/pages/DashBoard/Project/Interview/index.jsx, src/pages/DashBoard/Project/Participate/index.jsx, src/pages/DashBoard/Project/Proceeding/index.jsx, src/pages/DashBoard/Project/Tuning/index.jsx, src/pages/Main/index.jsx
=> 모든 프로젝트 리스트 페이지 배열 순서 변경

src/App.jsx, src/components/ListFreelancer/index.jsx, src/components/MenuBar/style.js, src/pages/ErrorPage/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/Partner/PartnerList/index.jsx
feat: adding Error page + cleaning up some code
=> feat: adding Error page + cleaning up some code

src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/MyBoardContact/ContactOneOnOne/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/Certificate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProfileIntro/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProjectHistory/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/SkillLists/index.jsx, src/pages/Project/ProjectNewDetail/index.jsx, src/utils/config/api.js
feat: fixing util/config for ROOT URL
=> feat: fixing util/config for ROOT URL

src/utils/config/api.js
=> feat: API base URL changed

src/components/Button/FilterButton/index.jsx, src/components/FreelancerDetail/index.jsx, src/components/ListFreelancer/index.jsx, src/layouts/Header/Freelancer/index.jsx, src/layouts/Header/Freelancer/style.js, src/layouts/Header/index.jsx, src/layouts/Header/style.js, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/MyBoardFreelancer/index.jsx, src/pages/Partner/PartnerList/index.jsx, src/pages/Project/ProjectList/index.jsx, src/styles/GlobalStyles.js
feat: fixing bugs + adding filtering API + header styling
=> feat: fixing bugs + adding filtering API + header styling

src/App.jsx, src/components/ListFreelancer/index.jsx, src/components/ListFreelancer/style.js, src/pages/Partner/PartnerDetail/index.jsx
feat: adding freelancer/ 상세보기 page
=> feat: adding freelancer/ 상세보기 page

src/pages/Project/ProjectList/index.jsx
1. 프로젝트 리스트 버튼 누를때마다 데이터 변경 및 border 변경
2. 프로젝트 둘러보기 누르면 프로젝트 리스트 데이터 변경 및 border 변경
=> 프로젝트 보기 무한 스크롤 및 필터 추가하기 제외 하고 완료

src/components/ListFreelancer/index.jsx, src/layouts/Footer/index.jsx, src/layouts/Footer/style.js, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/Partner/PartnerDetail/index.jsx, src/utils/config/api.js, src/utils/helpers.js
feat: adding page/partner-detail + adding helpers JS
=> feat: adding page/partner-detail + adding helpers JS

src/pages/Main/Freelancer/index.jsx
feat: add API - /project-index-list
=> feat: add API - /project-index-list

src/components/Button/FilterButton/index.jsx, src/components/ListFreelancer/index.jsx, src/components/Modal/FreelancerFilter/index.jsx, src/components/Modal/FreelancerFilter/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/EducationInfoTemplate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx, src/pages/Partner/PartnerList/index.jsx
feat: fixing bugs 1)  EnducationInfo Component + 2) parter-list filter
=> feat: fixing bugs 1)  EnducationInfo Component + 2) parter-list filter

src/pages/MyBoardFreelancer/MyBoardProfileModify/CareerInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/Certificate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/EducationInfoTemplate/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProjectHistory/index.jsx, src/pages/Partner/PartnerList/index.jsx, src/utils/config/api.js
feat: fixing bugs for the default datas
=> feat: fixing bugs for the default datas

src/pages/MyBoardFreelancer/MyBoardProfileModify/EducationInfo/index.jsx
=> cleaning up typo

src/components/Search/index.jsx, src/components/SearchProjectList/index.jsx, src/pages/Search/FreelancerSearch/index.jsx, src/pages/Search/index.jsx, src/styles/Ecard.js
feat: adding page/Search(Main) - freelancer + separating files
=> feat: adding page/Search(Main) - freelancer + separating files

src/components/Search/index.jsx, src/components/Search/style.js, src/components/SearchProjectList/index.jsx, src/layouts/Header/Freelancer/style.js, src/layouts/Header/Search/index.jsx, src/pages/Main/Freelancer/Designer/index.jsx, src/pages/Main/Freelancer/Developer/index.jsx, src/pages/Main/Freelancer/ETC/index.jsx, src/pages/Main/Freelancer/Planner/index.jsx, src/pages/Main/Freelancer/Publisher/index.jsx, src/pages/Main/Freelancer/index.jsx, src/pages/Main/Freelancer/style.js, src/pages/Partner/PartnerList/FilterButton/index.jsx, src/pages/Partner/PartnerList/FreelancerFilter/index.jsx, src/pages/Partner/PartnerList/index.jsx, src/pages/Search/FreelancerSearch/index.jsx, src/pages/Search/index.jsx, src/utils/config/api.js
feat: added Header for page/Search + search filter
=> feat: added Header for page/Search + search filter

src/components/Modal/ProjectListModal/index.jsx, src/pages/Main/Freelancer/index.jsx, src/pages/Project/ProjectList/index.jsx, src/pages/Search/FreelancerSearch/index.jsx, src/utils/constants/freelancerFilter/index.js, src/utils/constants/freelancerPosition/developer.js, src/utils/constants/freelancerPosition/publisher.js, src/utils/helpers.js
feat: Main-> filter location.search
=> feat: Main-> filter location.search

src/components/ListFreelancer/index.jsx, src/pages/Partner/PartnerList/index.jsx, src/pages/Search/FreelancerSearch/index.jsx, src/styles/Page.js, src/utils/config/api.js
feat: adding infinite scroll to pages/Search
=> feat: adding infinite scroll to pages/Search

src/components/Card/ProjectCard/index.jsx, src/components/ListPortfolio/index.jsx, src/components/Myboard/FreelancerMyboard/index.jsx, src/components/Myboard/FreelancerMyboard/style.js, src/components/Myboard/MyBoardEcards/index.jsx, src/components/Myboard/MyBoardEcards/style.js, src/pages/MyBoardFreelancer/MyBoardManageProject/index.jsx, src/pages/MyBoardFreelancer/MyBoardOnGoing/index.jsx, src/pages/MyBoardFreelancer/MyBoardOnGoing/style.js, src/pages/MyBoardFreelancer/index.jsx
=> feat: adding wish-list  API

src/components/ListFreelancer/WishList/index.jsx, src/components/ListFreelancer/index.jsx, src/components/ListFreelancer/style.js, src/components/ListPortfolio/index.jsx, src/components/Myboard/FreelancerMyboard/index.jsx, src/utils/config/api.js
feat: modifying pages/wish-list API
=> feat: modifying pages/wish-list API

src/components/ListPortfolio/index.jsx, src/layouts/Header/Company/style.js, src/layouts/Header/Freelancer/style.js, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/style.js, src/pages/MyBoardFreelancer/MyBoardOnGoing/index.jsx, src/pages/MyBoardFreelancer/MyBoardOnGoing/style.js, src/pages/MyBoardFreelancer/MyBoardProfile/index.jsx, src/pages/MyBoardFreelancer/MyBoardProfile/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProfileIntro/index.jsx
feat: adding thumbnail img API
=> feat: adding thumbnail img API

src/components/ListFreelancer/index.jsx, src/layouts/Header/Freelancer/index.jsx, src/layouts/Header/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/index.jsx, src/pages/Partner/PartnerDetail/index.jsx, src/utils/config/api.js
feat: fixing bugs for thumbnail IMG API
=> feat: fixing bugs for thumbnail IMG API

src/components/ListPortfolio/index.jsx, src/layouts/Header/Freelancer/index.jsx, src/layouts/Header/Freelancer/style.js, src/layouts/Header/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/style.js, src/pages/MyBoardFreelancer/MyBoardProfileModify/ProfileIntro/index.jsx, src/styles/Page.js
feat: file API + likes button API
=> feat: file API + likes button API

src/components/ListPortfolio/index.jsx, src/components/Myboard/FreelancerMyboard/index.jsx, src/components/Myboard/MyBoardEcards/index.jsx, src/components/Project-Ecard/DesignEcard/index.jsx, src/components/Project-Ecard/Develop-Ecard/index.jsx, src/components/Project-Ecard/EtcEcard/index.jsx, src/components/Project-Ecard/PlanEcard/index.jsx, src/components/Project-Ecard/PublishEcard/index.jsx, src/components/Project-Ecard/index.jsx, src/components/Re-Project/index.jsx, src/layouts/Header/Freelancer/index.jsx, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/Project/ProjectList/index.jsx
feat: adding 찜 기능 for pages/main + pages/project-list
=> feat: adding 찜 기능 for pages/main + pages/project-list

src/components/ListPortfolio/index.jsx, src/components/Project-Ecard/index.jsx, src/components/Re-Project/index.jsx, src/pages/Project/ProjectList/index.jsx
feat: fixing bugs for 찜 기능 API - enterprise
=> feat: fixing bugs for 찜 기능 API - enterprise

src/components/ListPortfolio/index.jsx, src/pages/Main/Freelancer/index.jsx
feat: adding 찜 API for Main/freelancer
=> feat: adding 찜 API for Main/freelancer

src/components/ListPortfolio/index.jsx, src/pages/Login/index.jsx, src/pages/Project/ProjectNewDetail/index.jsx, src/utils/config/api.js
feat: fixing bugs for 중복 추가 -프로젝트+  SNS login
=> feat: fixing bugs for 중복 추가 -프로젝트+  SNS login

src/components/FreelancerDetail/index.jsx, src/components/Re-Freelancer/index.jsx, src/pages/Partner/PartnerDetail/index.jsx, src/utils/config/api.js
feat: adding partner-list details
=> feat: adding partner-list details

src/components/Modal/GridBottom/index.jsx, src/components/Modal/GridBottom/style.js, src/pages/Partner/PartnerList/index.jsx, src/pages/Search/FreelancerSearch/index.jsx
feat: adding router for gridbottom
=> feat: adding router for gridbottom

src/layouts/Header/Freelancer/style.js
feat: fixing bugs for search header div
=> feat: fixing bugs for search header div

src/pages/SignUp/Freelancer/index.jsx
feat: fixing bugs for signup/phone number
=> feat: fixing bugs for signup/phone number

src/pages/SignUp/Finish/index.jsx, src/pages/SignUp/Freelancer/index.jsx
=> feat: adding signup/finish

public/index.html, src/pages/MyBoardFreelancer/MyBoardAccount/index.jsx, src/pages/Project/index.jsx, src/styles/Page.js
feat: fixing bugs for myboard-account/PUT + styling for /project-list
=> feat: fixing bugs for myboard-account/PUT + styling for /project-list

src/pages/Search/FreelancerSearch/index.jsx, src/utils/config/api.js
feat: fixing bugs for pages/search - infinite scroll
=> feat: fixing bugs for pages/search - infinite scroll

src/pages/SignUp/Company/index.jsx, src/pages/SignUp/Finish/index.jsx, src/pages/SignUp/Freelancer/index.jsx
feat: adding page/signup for enterprise
=> feat: adding page/signup for enterprise
